questions = [{"question":"How many blue stripes are there on the U.S. flag?","a":"6","b":"7","c":"13","d":"0","answer":"4"},
{"question":"Grand Central Terminal, Park Avenue, New York is the world's","a":"largest railway station","b":"highest railway station","c":"longest railway station","d":"None of the above","answer":"1"},
{"question":"Hitler party which came into power in 1933 is known as","a":"Labour Party","b":"nazi Party","c":"Ku-Klux-Klan","d":"Democratic Party","answer":"2"},
{"question":"Friction can be reduced by changing from","a":"sliding to rolling","b":"rolling to sliding","c":"potential energy to kinetic energy","d":"dynamic to static","answer":"1"},
{"question":"The ozone layer restricts","a":"Visible light","b":"Infrared radiation","c":"X-rays and Gamma rays","d":"Ultraviolet radiation","answer":"4"},
{"question":"Filaria is caused by","a":"Mosquito","b":"Protozoa","c":"Bacteria","d":"Virus","answer":"1"},
{"question":"Fathometer is used to measure?","a":"Earthquakes","b":"Rainfall","c":"Ocean depth","d":"Sound intensity","answer":"3"},
{"question":"For galvanizing iron which of the following metals is used?","a":"Aluminium","b":"Copper","c":"Lead","d":"Zinc","answer":"4"},
{"question":"Excessive secretion from the pituitary gland in the children results in","a":"increased height","b":"retarded growth","c":"weakening of bones","d":"none of the above","answer":"1"},
{"question":"The treaty which ushered in NATO, was signed by the member nations at","a":"Geneva","b":"London","c":"Paris","d":"Washington","answer":"4"}]